#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:14.17.6

definitions:
    steps:
        - step: &lint
            name: Code linting
            script:
              - npm install eslint
              - npx eslint .
            caches:
              - node
        - step: &security_scan
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              - pipe: atlassian/git-secrets-scan:0.4.3
        - step: &build
              name: Build
              caches:
                  - node
              script:
                  - apt-get update
                  - apt-get install zip
                  - npm install
                  - npm run build
                  - zip -r application.zip . -x node_modules/\* .git/\*
              artifacts: 
                  - application.zip
pipelines:
  default:
    - parallel:
        - step: *build
        - step: *lint
        - step: *security_scan
  branches:
    master:
      - parallel:
        - step: *build
        #- step: *lint
        - step: *security_scan
      - step:
          name: Deploy to testing
          deployment: test
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:1.0.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME
                ZIP_FILE: 'application.zip'
                WAIT_INTERVAL: 60
                WARMUP_INTERVAL: 30
                WAIT: 'true'
                S3_BUCKET: $S3_BUCKET
