version: '3.3'

services:

  db:
    container_name: mysql-blockchain-middleware
    image: mysql:8.0
    platform: linux/amd64 # add that  only for Mackbook with M1 processor not necessary for windows
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'kx-blockchain-middleware-dev'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'FcA5Xy-B8t3X-Gw7kk'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
